### ISSUE TITLE
Missing dep: `babel-polyfill`

### ISSUE THREAD

**Issue by chpio** [Burnett01/node-moco#1]
the `babel-polyfill` dependency is not declared as a npm dependency, but gets imported in `utils.js`. also: `babel-polyfill` shouldn't be used in a library, please use `babel-runtime` instead.

**Comment by Burnett01** [comment]
Hey @chpio, thank you very much. Luckily this did not affect the **dist/** files but the dev files, such as **lib/**. I have added ``babel-runtime`` as a dependency and dropped ``babel-polyfill`` alltogether.

Will push it with the next release.
