### ISSUE TITLE
This Returns an empty string on http errors

### ISSUE THREAD

**Issue by chpio** [Burnett01/node-moco#2]
the api returns an empty string, no error, if the underlying http request has failed.

after a bit of digging into your custom http library, it seems that the host is responding with a non-200-http status:
```
statusCode: 403,
statusMessage: 'Forbidden',
```

**Comment by Burnett01** [comment]
@chpio  Thank you very much for forwarding this issue. I will take a closer look into this.

**Comment by Burnett01** [comment]
@chpio I was able to trigger a non-200 code (401 in this case) by using an invalid api-key.

The library responds with the corresponding error message.

![image](https://user-images.githubusercontent.com/1208707/65973634-f2f09f00-e46b-11e9-88c8-adcd2d8c52c2.png)

I'm curious to know how you triggered the 403 response, so I can check that.

The nodeback ``err`` param and promise ``catch(err)`` method are only used when there is a critical (serverside) error such as 500 (50x). Regular service errors are forwarded to the first nodeback param or to the ``then()`` method for promises.

**Comment by Burnett01** [comment]
> Regular service errors are forwarded to the first nodeback param or to the then() method for promises.

The next version will change that. Such as with 50x status errors, additional non 200 errors will also lead to rejecting the promise/passing the error object to the first nodeback pram. This eliminates the need for manually checking 40x and other non 200 responses.

**Comment by Burnett01** [comment]
Resolved with extended-request version 1.6.0  https://github.com/Burnett01/extended-request/releases/tag/1.6.0
